
export const storyActions = {
    SET_STORY: 'SET_STORY',
    SET_STORIES: 'SET_STORIES',
    ADD_STORY: 'ADD_STORY',
    UPDATE_STORY: 'UPDATE_STORY',
    REMOVE_STORY: 'REMOVE_STORY',
    SET_IS_LOADING: 'SET_IS_LOADING',
    REMOVE_STORY: 'REMOVE_STORY',
    SET_FILTERBY: 'SET_FILTERBY',
}
export const quoteActions = {
    SET_QUOTES: 'SET_QUOTES',
    SET_QUOTES_PAGE: 'SET_QUOTES_PAGE',
    TOGGLE_SHARING: 'TOGGLE_SHARING'
}